# Default design configurations mirroring the RL environment layout.
#
# Each entry defines one design target and includes design-specific ECO action
# spaces and observation normalization ranges.

DESIGN_CONFIGS = {'demo': {'max_iterations_per_episode': 10,
          'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
          'action_spaces': {},
          'normalization_ranges': {'setup_critical_path_slack': {'min': -100.0, 'max': 100.0},
                                   'setup_total_negative_slack': {'min': -100000.0, 'max': 0.0},
                                   'setup_violating_paths': {'min': 0.0, 'max': 10000.0},
                                   'hold_critical_path_slack': {'min': -100.0, 'max': 100.0},
                                   'hold_total_negative_slack': {'min': -100000.0, 'max': 0.0},
                                   'hold_violating_paths': {'min': 0.0, 'max': 10000.0},
                                   'total_power': {'min': 0.0, 'max': 1.0},
                                   'internal_power': {'min': 0.0, 'max': 1.0},
                                   'switching_power': {'min': 0.0, 'max': 1.0},
                                   'leakage_power': {'min': 0.0, 'max': 1.0},
                                   'total_cell_area': {'min': 0.0, 'max': 100000.0},
                                   'design_area': {'min': 0.0, 'max': 100000.0},
                                   'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                   'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                   'iteration': {'min': 0.0, 'max': 10.0}},
          'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
          'env_kwargs': {'base_path': 'data/demo',
                         'design_name': 'demo'}},
 'NV_NVDLA_partition_m': {'max_iterations_per_episode': 10,
                                'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                                'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                             'actions': ['gate_sizing',
                                                                         'buffer_insertion',
                                                                         'gate_sizing_side_load'],
                                                             'cell_classes': ['combinational',
                                                                            'sequential',
                                                                            'clock_tree'],
                                                             'site_mode': ['open_slot', 'occupied_slot'],
                                                             'area_cap': {'low': 2, 'high': 20.0},
                                                             'slack_above': {'low': 0, 'high': 1000},
                                                             'slack_below': {'low': -1000, 'high': 0}},
                                                  'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                                            'cell_classes': ['combinational', 'sequential'],
                                                            'power_scope': ['total', 'dynamic', 'leakage'],
                                                            'setup_guard': {'low': -1000, 'high': 0.0}},
                                                  'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                                           'cell_classes': ['combinational',
                                                                          'sequential',
                                                                          'clock_tree'],
                                                           'setup_guard': {'low': -1000, 'high': 0.0}}},
                                'normalization_ranges': {'setup_critical_path_slack': {'min': -1000, 'max': 1000},
                                                         'setup_total_negative_slack': {'min': -25000, 'max': 0.0},
                                                         'setup_violating_paths': {'min': 0, 'max': 1000},
                                                         'hold_critical_path_slack': {'min': -1000, 'max': 1000},
                                                         'hold_total_negative_slack': {'min': -25000, 'max': 0.0},
                                                         'hold_violating_paths': {'min': 0, 'max': 1000},
                                                         'total_power': {'min': 0.0, 'max': 0.02},
                                                         'internal_power': {'min': 0.0, 'max': 0.02},
                                                         'switching_power': {'min': 0.0, 'max': 0.02},
                                                         'leakage_power': {'min': 0.0, 'max': 1e-05},
                                                         'total_cell_area': {'min': 0.0, 'max': 5000.0},
                                                         'design_area': {'min': 0.0, 'max': 5000.0},
                                                         'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                                         'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                                         'iteration': {'min': 0, 'max': 10}},
                                'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                                'env_kwargs': {'base_path': 'data/NV_NVDLA_partition_m',
                                               'design_name': 'NV_NVDLA_partition_m'}},
 'NV_NVDLA_partition_p': {'max_iterations_per_episode': 10,
                                'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                                'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                             'actions': ['gate_sizing',
                                                                         'buffer_insertion',
                                                                         'gate_sizing_side_load'],
                                                             'cell_classes': ['combinational',
                                                                            'sequential',
                                                                            'clock_tree'],
                                                             'site_mode': ['open_slot', 'occupied_slot'],
                                                             'area_cap': {'low': 2, 'high': 20.0},
                                                             'slack_above': {'low': 0, 'high': 1000},
                                                             'slack_below': {'low': -1000, 'high': 0}},
                                                  'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                                            'cell_classes': ['combinational', 'sequential'],
                                                            'power_scope': ['total', 'dynamic', 'leakage'],
                                                            'setup_guard': {'low': -1000, 'high': 0.0}},
                                                  'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                                           'cell_classes': ['combinational',
                                                                          'sequential',
                                                                          'clock_tree'],
                                                           'setup_guard': {'low': -1000, 'high': 0.0}}},
                                'normalization_ranges': {'setup_critical_path_slack': {'min': -1000, 'max': 1000},
                                                         'setup_total_negative_slack': {'min': -250000, 'max': 0.0},
                                                         'setup_violating_paths': {'min': 0, 'max': 1000},
                                                         'hold_critical_path_slack': {'min': -1000, 'max': 1000},
                                                         'hold_total_negative_slack': {'min': -250000, 'max': 0.0},
                                                         'hold_violating_paths': {'min': 0, 'max': 1000},
                                                         'total_power': {'min': 0.0, 'max': 0.02},
                                                         'internal_power': {'min': 0.0, 'max': 0.02},
                                                         'switching_power': {'min': 0.0, 'max': 0.02},
                                                         'leakage_power': {'min': 0.0, 'max': 1e-05},
                                                         'total_cell_area': {'min': 0.0, 'max': 12000.0},
                                                         'design_area': {'min': 0.0, 'max': 12000.0},
                                                         'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                                         'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                                         'iteration': {'min': 0, 'max': 10}},
                                'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                                'env_kwargs': {'base_path': 'data/NV_NVDLA_partition_p',
                                               'design_name': 'NV_NVDLA_partition_p'}},
 'ariane136': {'max_iterations_per_episode': 10,
                     'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                     'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                  'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                  'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                  'site_mode': ['open_slot', 'occupied_slot'],
                                                  'area_cap': {'low': 2, 'high': 20.0},
                                                  'slack_above': {'low': 0, 'high': 1000},
                                                  'slack_below': {'low': -1000, 'high': 0}},
                                       'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                                 'cell_classes': ['combinational', 'sequential'],
                                                 'power_scope': ['total', 'dynamic', 'leakage'],
                                                 'setup_guard': {'low': -1000, 'high': 0.0}},
                                       'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'setup_guard': {'low': -1000, 'high': 0.0}}},
                     'normalization_ranges': {'setup_critical_path_slack': {'min': -1000, 'max': 1000},
                                              'setup_total_negative_slack': {'min': -260000, 'max': 0.0},
                                              'setup_violating_paths': {'min': 0, 'max': 1000},
                                              'hold_critical_path_slack': {'min': -1000, 'max': 1000},
                                              'hold_total_negative_slack': {'min': -260000, 'max': 0.0},
                                              'hold_violating_paths': {'min': 0, 'max': 1000},
                                              'total_power': {'min': 0.0, 'max': 1},
                                              'internal_power': {'min': 0.0, 'max': 1},
                                              'switching_power': {'min': 0.0, 'max': 1},
                                              'leakage_power': {'min': 0.0, 'max': 0.03},
                                              'total_cell_area': {'min': 0.0, 'max': 50000.0},
                                              'design_area': {'min': 0.0, 'max': 50000.0},
                                              'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                              'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                              'iteration': {'min': 0, 'max': 10}},
                     'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                     'env_kwargs': {'base_path': 'data/ariane136',
                                    'design_name': 'ariane136'}},
 'mempool_tile_wrap': {'max_iterations_per_episode': 10,
                             'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                             'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                          'actions': ['gate_sizing',
                                                                      'buffer_insertion',
                                                                      'gate_sizing_side_load'],
                                                          'cell_classes': ['combinational',
                                                                         'sequential',
                                                                         'clock_tree'],
                                                          'site_mode': ['open_slot', 'occupied_slot'],
                                                          'area_cap': {'low': 2, 'high': 20.0},
                                                          'slack_above': {'low': 0, 'high': 1000},
                                                          'slack_below': {'low': -1000, 'high': 0}},
                                               'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                                         'cell_classes': ['combinational', 'sequential'],
                                                         'power_scope': ['total', 'dynamic', 'leakage'],
                                                         'setup_guard': {'low': -1000, 'high': 0.0}},
                                               'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                                        'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                        'setup_guard': {'low': -1000, 'high': 0.0}}},
                             'normalization_ranges': {'setup_critical_path_slack': {'min': -1000, 'max': 1000},
                                                      'setup_total_negative_slack': {'min': -2600000, 'max': 0.0},
                                                      'setup_violating_paths': {'min': 0, 'max': 1000},
                                                      'hold_critical_path_slack': {'min': -1000, 'max': 1000},
                                                      'hold_total_negative_slack': {'min': -2600000, 'max': 0.0},
                                                      'hold_violating_paths': {'min': 0, 'max': 1000},
                                                      'total_power': {'min': 0.0, 'max': 0.1},
                                                      'internal_power': {'min': 0.0, 'max': 0.1},
                                                      'switching_power': {'min': 0.0, 'max': 0.1},
                                                      'leakage_power': {'min': 0.0, 'max': 0.003},
                                                      'total_cell_area': {'min': 0.0, 'max': 50000.0},
                                                      'design_area': {'min': 0.0, 'max': 50000.0},
                                                      'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                                      'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                                      'iteration': {'min': 0, 'max': 10}},
                             'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                             'env_kwargs': {'base_path': 'data/mempool_tile_wrap',
                                            'design_name': 'mempool_tile_wrap'}},
 'aes_256': {'max_iterations_per_episode': 10,
                   'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                   'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'site_mode': ['open_slot', 'occupied_slot'],
                                                'area_cap': {'low': 2, 'high': 20.0},
                                                'slack_above': {'low': 0, 'high': 100},
                                                'slack_below': {'low': -100, 'high': 0}},
                                     'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                               'cell_classes': ['combinational', 'sequential'],
                                               'power_scope': ['total', 'dynamic', 'leakage'],
                                               'setup_guard': {'low': -100, 'high': 0.0}},
                                     'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                              'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                              'setup_guard': {'low': -100, 'high': 0.0}}},
                   'normalization_ranges': {'setup_critical_path_slack': {'min': -100, 'max': 100},
                                            'setup_total_negative_slack': {'min': -100000, 'max': 0.0},
                                            'setup_violating_paths': {'min': 0, 'max': 10000},
                                            'hold_critical_path_slack': {'min': -1000, 'max': 1000},
                                            'hold_total_negative_slack': {'min': -100000, 'max': 0.0},
                                            'hold_violating_paths': {'min': 0, 'max': 10000},
                                            'total_power': {'min': 0.0, 'max': 1},
                                            'internal_power': {'min': 0.0, 'max': 1},
                                            'switching_power': {'min': 0.0, 'max': 1},
                                            'leakage_power': {'min': 0.0, 'max': 3e-05},
                                            'total_cell_area': {'min': 0.0, 'max': 40000.0},
                                            'design_area': {'min': 0.0, 'max': 40000.0},
                                            'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                            'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                            'iteration': {'min': 0, 'max': 10}},
                   'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                   'env_kwargs': {'base_path': 'data/aes_256',
                                  'design_name': 'aes_256'}},
 'hidden1': {'max_iterations_per_episode': 10,
                   'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                   'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'site_mode': ['open_slot', 'occupied_slot'],
                                                'area_cap': {'low': 2, 'high': 20.0},
                                                'slack_above': {'low': 0, 'high': 100},
                                                'slack_below': {'low': -100, 'high': 0}},
                                     'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                               'cell_classes': ['combinational', 'sequential'],
                                               'power_scope': ['total', 'dynamic', 'leakage'],
                                               'setup_guard': {'low': -100, 'high': 0.0}},
                                     'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                              'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                              'setup_guard': {'low': -100, 'high': 0.0}}},
                   'normalization_ranges': {'setup_critical_path_slack': {'min': -200, 'max': 200},
                                            'setup_total_negative_slack': {'min': -50000, 'max': 0.0},
                                            'setup_violating_paths': {'min': 0, 'max': 1000},
                                            'hold_critical_path_slack': {'min': -200, 'max': 200},
                                            'hold_total_negative_slack': {'min': -50000, 'max': 0.0},
                                            'hold_violating_paths': {'min': 0, 'max': 1000},
                                            'total_power': {'min': 0.0, 'max': 0.1},
                                            'internal_power': {'min': 0.0, 'max': 0.1},
                                            'switching_power': {'min': 0.0, 'max': 0.1},
                                            'leakage_power': {'min': 0.0, 'max': 1e-05},
                                            'total_cell_area': {'min': 0.0, 'max': 10000.0},
                                            'design_area': {'min': 0.0, 'max': 10000.0},
                                            'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                            'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                            'iteration': {'min': 0, 'max': 10}},
                   'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                   'env_kwargs': {'base_path': 'data/hidden1',
                                  'design_name': 'hidden1'}},
 'hidden2': {'max_iterations_per_episode': 10,
                   'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                   'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'site_mode': ['open_slot', 'occupied_slot'],
                                                'area_cap': {'low': 2, 'high': 20.0},
                                                'slack_above': {'low': 0, 'high': 200},
                                                'slack_below': {'low': -200, 'high': 0}},
                                     'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                               'cell_classes': ['combinational', 'sequential'],
                                               'power_scope': ['total', 'dynamic', 'leakage'],
                                               'setup_guard': {'low': -200, 'high': 0.0}},
                                     'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                              'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                              'setup_guard': {'low': -200, 'high': 0.0}}},
                   'normalization_ranges': {'setup_critical_path_slack': {'min': -200, 'max': 200},
                                            'setup_total_negative_slack': {'min': -200000, 'max': 0.0},
                                            'setup_violating_paths': {'min': 0, 'max': 3000},
                                            'hold_critical_path_slack': {'min': -200, 'max': 200},
                                            'hold_total_negative_slack': {'min': -200000, 'max': 0.0},
                                            'hold_violating_paths': {'min': 0, 'max': 1000},
                                            'total_power': {'min': 0.0, 'max': 1},
                                            'internal_power': {'min': 0.0, 'max': 1},
                                            'switching_power': {'min': 0.0, 'max': 1},
                                            'leakage_power': {'min': 0.0, 'max': 0.02},
                                            'total_cell_area': {'min': 0.0, 'max': 40000.0},
                                            'design_area': {'min': 0.0, 'max': 40000.0},
                                            'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                            'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                            'iteration': {'min': 0, 'max': 10}},
                   'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                   'env_kwargs': {'base_path': 'data/hidden2',
                                  'design_name': 'hidden2'}},
 'hidden3': {'max_iterations_per_episode': 10,
                   'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                   'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'site_mode': ['open_slot', 'occupied_slot'],
                                                'area_cap': {'low': 2, 'high': 20.0},
                                                'slack_above': {'low': 0, 'high': 200},
                                                'slack_below': {'low': -200, 'high': 0}},
                                     'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                               'cell_classes': ['combinational', 'sequential'],
                                               'power_scope': ['total', 'dynamic', 'leakage'],
                                               'setup_guard': {'low': -200, 'high': 0.0}},
                                     'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                              'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                              'setup_guard': {'low': -200, 'high': 0.0}}},
                   'normalization_ranges': {'setup_critical_path_slack': {'min': -200, 'max': 200},
                                            'setup_total_negative_slack': {'min': -20000, 'max': 0.0},
                                            'setup_violating_paths': {'min': 0, 'max': 1000},
                                            'hold_critical_path_slack': {'min': -200, 'max': 200},
                                            'hold_total_negative_slack': {'min': -20000, 'max': 0.0},
                                            'hold_violating_paths': {'min': 0, 'max': 1000},
                                            'total_power': {'min': 0.0, 'max': 1},
                                            'internal_power': {'min': 0.0, 'max': 1},
                                            'switching_power': {'min': 0.0, 'max': 1},
                                            'leakage_power': {'min': 0.0, 'max': 0.1},
                                            'total_cell_area': {'min': 0.0, 'max': 100000.0},
                                            'design_area': {'min': 0.0, 'max': 1000000.0},
                                            'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                            'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                            'iteration': {'min': 0, 'max': 10}},
                   'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                   'env_kwargs': {'base_path': 'data/hidden3',
                                  'design_name': 'hidden3'}},
 'hidden5': {'max_iterations_per_episode': 10,
                   'action_space': {'low': 0.0, 'high': 1.0, 'dimension': 24},
                   'action_spaces': {'timing': {'violation_type': ['setup', 'hold'],
                                                'actions': ['gate_sizing', 'buffer_insertion', 'gate_sizing_side_load'],
                                                'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                                'site_mode': ['open_slot', 'occupied_slot'],
                                                'area_cap': {'low': 2, 'high': 20.0},
                                                'slack_above': {'low': 0, 'high': 200},
                                                'slack_below': {'low': -200, 'high': 0}},
                                     'power': {'actions': ['gate_sizing', 'buffer_removal'],
                                               'cell_classes': ['combinational', 'sequential'],
                                               'power_scope': ['total', 'dynamic', 'leakage'],
                                               'setup_guard': {'low': -200, 'high': 0.0}},
                                     'area': {'actions': ['gate_sizing', 'buffer_removal'],
                                              'cell_classes': ['combinational', 'sequential', 'clock_tree'],
                                              'setup_guard': {'low': -200, 'high': 0.0}}},
                   'normalization_ranges': {'setup_critical_path_slack': {'min': -200, 'max': 200},
                                            'setup_total_negative_slack': {'min': -200000, 'max': 0.0},
                                            'setup_violating_paths': {'min': 0, 'max': 3000},
                                            'hold_critical_path_slack': {'min': -200, 'max': 200},
                                            'hold_total_negative_slack': {'min': -200000, 'max': 0.0},
                                            'hold_violating_paths': {'min': 0, 'max': 3000},
                                            'total_power': {'min': 0.0, 'max': 1},
                                            'internal_power': {'min': 0.0, 'max': 1},
                                            'switching_power': {'min': 0.0, 'max': 1},
                                            'leakage_power': {'min': 0.0, 'max': 0.0001},
                                            'total_cell_area': {'min': 0.0, 'max': 40000.0},
                                            'design_area': {'min': 0.0, 'max': 300000.0},
                                            'remaining_budget': {'min': 0.0, 'max': 9999999999.0},
                                            'elapsed_runtime': {'min': 0.0, 'max': 99999999999.0},
                                            'iteration': {'min': 0, 'max': 10}},
                   'reward_weights': {'setup_tns': 3.0, 'hold_tns': 1.0, 'power': 1.0, 'area': 1.0},
                   'env_kwargs': {'base_path': 'data/hidden5',
                                  'design_name': 'hidden5'}}}
